mpiexec -n 1 python generate_data_strong_scalability.py 60
mpiexec -n 1 python generate_data_strong_scalability.py 180
mpiexec -n 1 python generate_data_strong_scalability.py 320
mpiexec -n 1 python generate_data_strong_scalability.py 640
mpiexec -n 2 python generate_data_strong_scalability.py 60
mpiexec -n 2 python generate_data_strong_scalability.py 180
mpiexec -n 2 python generate_data_strong_scalability.py 320
mpiexec -n 2 python generate_data_strong_scalability.py 640
mpiexec -n 3 python generate_data_strong_scalability.py 60
mpiexec -n 3 python generate_data_strong_scalability.py 180
mpiexec -n 3 python generate_data_strong_scalability.py 320
mpiexec -n 3 python generate_data_strong_scalability.py 640
mpiexec -n 4 python generate_data_strong_scalability.py 60
mpiexec -n 4 python generate_data_strong_scalability.py 180
mpiexec -n 4 python generate_data_strong_scalability.py 320
mpiexec -n 4 python generate_data_strong_scalability.py 640
mpiexec -n 5 python generate_data_strong_scalability.py 60
mpiexec -n 5 python generate_data_strong_scalability.py 180
mpiexec -n 5 python generate_data_strong_scalability.py 320
mpiexec -n 5 python generate_data_strong_scalability.py 640
mpiexec -n 6 python generate_data_strong_scalability.py 60
mpiexec -n 6 python generate_data_strong_scalability.py 180
mpiexec -n 6 python generate_data_strong_scalability.py 320
mpiexec -n 6 python generate_data_strong_scalability.py 640
